subscription addNewMessage($discussionId: Float!) {
    newMessage(discussionId: $discussionId) {
        id
        content
        user {
            id
            pseudo
            avatar {
                url
            }
        }
        created_at
        modified_at
    }
}
