query GetDiscussionsByGroupIdWithoutCtxUser($groupId: Float!) {
  getDiscussionsByGroupIdWithoutCtxUser(groupId: $groupId) {
    groupAvatarUrl
    groupName
    discussions {
      id
      userDiscussion {
        pseudo
        id
        avatar {
          url
        }
      }
    }
  }
}
