query GetGroupById($groupId: Int!) {
    getGroupById(groupId: $groupId) {
        id
        name
        created_at
        event_date
        userToGroups {
            is_admin
            user_id
            group_id
            user {
                avatar {
                    id
                    url
                    name
                }
                email
                pseudo
            }
        }
        avatar {
            id
            url
            name
        }
        discussions {
            id
            userDiscussion {
                id
            }
        }
    }
}
