query getMessagesByDisscution(
    $discussionId: Float!
    $offset: Int!
    $limit: Int!
) {
    getMessagesByDisscution(
        discussionId: $discussionId
        offset: $offset
        limit: $limit
    ) {
        id
        content
        user {
            id
            pseudo
            avatar {
                url
            }
        }
        created_at
        modified_at
    }
}
