query getMessagesByDisscution($discussionId: Float!) {
  getMessagesByDisscution(discussionId: $discussionId) {
    id
    content
    user {
      id
      pseudo
    }
    created_at
    modified_at
  }
}
