query UserGroups {
  userGroups {
    id
    name
    event_date
    created_at
    avatar {
      id
      name
      url
      name
    }
    userToGroups {
      user {
        id
        pseudo
        avatar {
          id
          name
          url
        }
      }
    }
  }
}
