name: build and push production client to dockerhub

on:
  push:
    branches:
      - dev

jobs:
  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            NEXT_PUBLIC_APOLLO_URI=http://localhost:4001
          context: "{{defaultContext}}:frontend"
          file: "Dockerfile.production"
          tags: crazygift2024/crazygift-client:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
